"""Array-level JAX kernels shared by eager and compiled patch operations."""

from .basic import (
    abs_kernel,
    add_kernel,
    angle_kernel,
    apply_1d_weight_kernel,
    clip_kernel,
    conj_kernel,
    flip_kernel,
    identity_kernel,
    imag_kernel,
    real_kernel,
    roll_kernel,
    scale_kernel,
    standardize_kernel,
)
from .filters import (
    design_pass_filter_sos,
    gaussian_filter_kernel,
    hampel_filter_callback_kernel,
    hampel_filter_kernel,
    is_finite_array,
    pass_filter_default_padlen,
    pass_filter_initial_state,
    pass_filter_kernel,
)
from .signal import (
    detrend_kernel,
    differentiate_kernel,
    integrate_kernel,
    normalize_kernel,
    validate_detrend_type,
)
from .spectral import (
    banded_stft_kernel,
    dft_kernel,
    envelope_kernel,
    hilbert_kernel,
    idft_kernel,
    whiten_kernel,
)

__all__ = [
    "abs_kernel",
    "add_kernel",
    "angle_kernel",
    "apply_1d_weight_kernel",
    "banded_stft_kernel",
    "clip_kernel",
    "conj_kernel",
    "design_pass_filter_sos",
    "detrend_kernel",
    "differentiate_kernel",
    "dft_kernel",
    "envelope_kernel",
    "flip_kernel",
    "gaussian_filter_kernel",
    "hampel_filter_callback_kernel",
    "hampel_filter_kernel",
    "hilbert_kernel",
    "identity_kernel",
    "idft_kernel",
    "imag_kernel",
    "integrate_kernel",
    "is_finite_array",
    "normalize_kernel",
    "pass_filter_default_padlen",
    "pass_filter_initial_state",
    "pass_filter_kernel",
    "real_kernel",
    "roll_kernel",
    "scale_kernel",
    "standardize_kernel",
    "validate_detrend_type",
    "whiten_kernel",
]
